### ISSUE TITLE
Support linux bang?

### ISSUE THREAD

**Issue by AnonGhostID** [Sxp-ID/litespam#1]
Ane user linux, gaisa dideploy dilinux, karna diencode, tolong lah support linux, ga cuma termux doang hehehe.
![image](https://github.com/Sxp-ID/litespam/assets/32584610/64d922cd-aeb6-4bf2-be47-6967dd3994c2)

**Comment by Sxp-ID** [comment]
> Ane user linux, gaisa dideploy dilinux, karna diencode, tolong lah support linux, ga cuma termux doang hehehe. ![image](https://private-user-images.githubusercontent.com/32584610/339826161-64d922cd-aeb6-4bf2-be47-6967dd3994c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzODA4NzQsIm5iZiI6MTcxODM4MDU3NCwicGF0aCI6Ii8zMjU4NDYxMC8zMzk4MjYxNjEtNjRkOTIyY2QtYWViNi00YmYyLWJlNDctNjk2N2RkMzk5NGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE1NTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkM2I4YTg3MWZjMDlkNGU3ODQwNmQ2MmJiMTM0NDg5NGEwOTgyOTdhYWMxZTc1MDdlNzBkYTA5MjlmYjYyOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jJTqNlI5ckvW4pE7xrGcuxbAb4zrvCvaznERu9yoliM)

Kalo saya punya laptop atau pc/komputer mah pasti bakal saya bikin support juga biar bisa dijalanin di linux, tapi saya cuman bikin script nya di hp dan cuman pake hp (apk termux) doang jadi takutnya untuk code² nya itu gak support buat run di linux. Mohon maaf dah wkwk saya juga bingung lumayan banyak yg req kek gini tapi ya mau gimana lagi :v
